{{- if .Values.application-service.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: application-service
  labels:
    app: application-service
spec:
  replicas: {{ .Values.application-service.replicaCount }}
  selector:
    matchLabels:
      app: application-service
  template:
    metadata:
      labels:
        app: application-service
    spec:
      containers:
        - name: application-service
          image: {{ include "hackathon-apps.image" (dict "Values" .Values "repository" .Values.application-service.image.repository) }}
          imagePullPolicy: {{ .Values.application-service.image.pullPolicy }}
          ports:
            - containerPort: 3001
          resources:
            {{- toYaml .Values.application-service.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: application-service
  labels:
    app: application-service
spec:
  type: {{ .Values.application-service.service.type }}
  ports:
    - port: {{ .Values.application-service.service.port }}
      targetPort: 3001
      protocol: TCP
      name: http
  selector:
    app: application-service
{{- end }}
