{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hackathon-apps-ingress
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.className }}
    {{- if .Values.ingress.useNginxRewrite }}
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    {{- end }}
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if .Values.ingress.hosts }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | default "" }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ if $.Values.ingress.useNginxRewrite }}{{ .path }}(/|$)(.*){{ else }}{{ .path }}{{ end }}
            pathType: {{ if $.Values.ingress.useNginxRewrite }}ImplementationSpecific{{ else }}{{ .pathType }}{{ end }}
            backend:
              service:
                name: {{ .service }}
                port:
                  number: {{ (index $.Values .service).service.port }}
          {{- end }}
    {{- end }}
  {{- end }}
{{- end }}
