{{- if .Values.patient-service.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: patient-service
  labels:
    app: patient-service
spec:
  replicas: {{ .Values.patient-service.replicaCount }}
  selector:
    matchLabels:
      app: patient-service
  template:
    metadata:
      labels:
        app: patient-service
    spec:
      containers:
        - name: patient-service
          image: {{ include "hackathon-apps.image" (dict "Values" .Values "repository" .Values.patient-service.image.repository) }}
          imagePullPolicy: {{ .Values.patient-service.image.pullPolicy }}
          ports:
            - containerPort: 3000
          resources:
            {{- toYaml .Values.patient-service.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: patient-service
  labels:
    app: patient-service
spec:
  type: {{ .Values.patient-service.service.type }}
  ports:
    - port: {{ .Values.patient-service.service.port }}
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: patient-service
{{- end }}
