global:
  imageRegistry: ""  
  imageTag: "latest"


ingress:
  enabled: true
  className: "gce"  
  useNginxRewrite: false  
  annotations:
    kubernetes.io/ingress.class: "gce"
  hosts:
    - host: ""  
      paths:
        - path: /application
          pathType: Prefix
          service: application-service
        - path: /patient
          pathType: Prefix
          service: patient-service
        - path: /order
          pathType: Prefix
          service: order-service

application-service:
  enabled: true
  replicaCount: 1
  image:
    repository: application-service
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 3001
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

patient-service:
  enabled: true
  replicaCount: 1
  image:
    repository: patient-service
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 3000
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

order-service:
  enabled: true
  replicaCount: 1
  image:
    repository: order-service
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8080
  resources:
    limits:
      cpu: 300m
      memory: 384Mi
    requests:
      cpu: 150m
      memory: 256Mi
